
global:
    log_dir: null # Default /var/log/ehdtd-daemon
    run_dir: null # Default /run/ehdtd-daemon
    debug: false

db_data:
  db_type: '_DBC_DBTYPE_'  # postgresql, pgsql, mysql
  db_name: '_DBC_DBNAME_'
  db_user: '_DBC_DBUSER_'
  db_pass: '_DBC_DBPASS_'
  db_host: '_DBC_DBSERVER_'
  db_port: '_DBC_DBPORT_'

exchanges:
  binance:
    trading_type: 'SPOT' # Only support SPOT

    fetch_data:
      - symbol: BTC/USDT
        interval: 1m
      - symbol: LTC/USDT
        interval: 1m

      - symbol: BTC/USDT
        interval: 5m
      - symbol: LTC/USDT
        interval: 5m

