#!/bin/bash

RPL=/usr/bin/rpl
CP=/bin/cp
RM=/bin/rm
USERADD=/usr/sbin/useradd
USERDEL=/usr/sbin/userdel
OPENSSL=/usr/bin/openssl
CHOWN=/bin/chown
CHMOD=/bin/chmod
MKDIR=/bin/mkdir
LN=/bin/ln
CAT=/bin/cat
ECHO=/bin/echo
MKTEMP=/bin/mktemp
FIND=/usr/bin/find
PWGEN=/usr/bin/pwgen
BASENAME=/usr/bin/basename
UPDATE_RC_D=/usr/sbin/update-rc.d
SYSTEMCTL=/bin/systemctl

####################################################################################

permisos_directorio()
{
    directorio=$1
    usuario=$2
    grupo=$3
    p_archivo=$4
    p_directorio=$5
    if [ -d ${directorio} ]
    then
        ${CHOWN} -R ${usuario}:${grupo} ${directorio}
        ${CHMOD} ${p_directorio} ${directorio}
        ${FIND} ${directorio} -type d -exec chmod $p_directorio {} \;
        ${FIND} ${directorio} -type f -exec chmod $p_archivo {} \;
    else
        ${MKDIR} -p ${directorio}
        ${CHOWN} -R ${usuario}:${grupo} ${directorio}
        ${CHMOD} ${p_directorio} ${directorio}
    fi
}

configure_martingale()
{

    for martingale_config_files in ${MARTINGALE_CONFIG_FILES}
    do
        CONFIG_FILE_IN=${ROOT_DIR}usr/share/doc/${SOFT_NAME}/skels/${martingale_config_files}
        CONFIG_FILE_OUT=${ROOT_DIR}etc/${SOFT_NAME}/${martingale_config_files}
        
        if [ "${martingale_config_files}" = "${SOFT_NAME}" ]
        then
            CONFIG_FILE_OUT=${ROOT_DIR}etc/default/${martingale_config_files}
        fi
        
        if ! [ -f ${CONFIG_FILE_OUT} ]
        then
            if ! [ "${martingale_config_files}" = "postgresql-config.php" ]
            then
                cat ${CONFIG_FILE_IN} > ${CONFIG_FILE_OUT}
                ${CHOWN} ${SYSTEM_USER}:root ${CONFIG_FILE_OUT}
                ${CHMOD} 0644 ${CONFIG_FILE_OUT}
            fi
        fi
    done
    
    MARTINGALE_DIR=${ROOT_DIR}etc/${SOFT_NAME}
    MARTINGALE_DIR_USR=${SYSTEM_USER}
    MARTINGALE_DIR_GRP=${SYSTEM_USER}
    MARTINGALE_DIR_PF=0600
    MARTINGALE_DIR_PD=0700
    permisos_directorio ${MARTINGALE_DIR} ${MARTINGALE_DIR_USR} ${MARTINGALE_DIR_GRP} ${MARTINGALE_DIR_PF} ${MARTINGALE_DIR_PD}
    
    MARTINGALE_DIR=${ROOT_DIR}usr/share/${SOFT_NAME}
    MARTINGALE_DIR_USR=${SYSTEM_USER}
    MARTINGALE_DIR_GRP=${SYSTEM_USER}
    MARTINGALE_DIR_PF=0600
    MARTINGALE_DIR_PD=0700
    permisos_directorio ${MARTINGALE_DIR} ${MARTINGALE_DIR_USR} ${MARTINGALE_DIR_GRP} ${MARTINGALE_DIR_PF} ${MARTINGALE_DIR_PD}

    MARTINGALE_DIR=${ROOT_DIR}usr/share/doc/${SOFT_NAME}
    MARTINGALE_DIR_USR=${SYSTEM_USER}
    MARTINGALE_DIR_GRP=${SYSTEM_USER}
    MARTINGALE_DIR_PF=0600
    MARTINGALE_DIR_PD=0700
    permisos_directorio ${MARTINGALE_DIR} ${MARTINGALE_DIR_USR} ${MARTINGALE_DIR_GRP} ${MARTINGALE_DIR_PF} ${MARTINGALE_DIR_PD}
    
    MARTINGALE_DIR=${ROOT_DIR}var/lib/${SOFT_NAME}
    MARTINGALE_DIR_USR=${SYSTEM_USER}
    MARTINGALE_DIR_GRP=${SYSTEM_USER}
    MARTINGALE_DIR_PF=0600
    MARTINGALE_DIR_PD=0700
    permisos_directorio ${MARTINGALE_DIR} ${MARTINGALE_DIR_USR} ${MARTINGALE_DIR_GRP} ${MARTINGALE_DIR_PF} ${MARTINGALE_DIR_PD}
    
    MARTINGALE_DIR=${ROOT_DIR}var/log/${SOFT_NAME}
    MARTINGALE_DIR_USR=${SYSTEM_USER}
    MARTINGALE_DIR_GRP=${SYSTEM_USER}
    MARTINGALE_DIR_PF=0600
    MARTINGALE_DIR_PD=0700
    permisos_directorio ${MARTINGALE_DIR} ${MARTINGALE_DIR_USR} ${MARTINGALE_DIR_GRP} ${MARTINGALE_DIR_PF} ${MARTINGALE_DIR_PD}
    
    for martingale_exec_files in ${MARTINGALE_EXEC_FILES}
    do
        ${CHOWN} ${SYSTEM_USER}:root ${martingale_exec_files}
        ${CHMOD} 0550 ${martingale_exec_files}
    done
    
    if [ -d /run/systemd/system ]
    then
        if ! ${SYSTEMCTL} is-enabled ${SYSTEMD_SERVICE} 1>/dev/null 2>/dev/null
        then
            ${SYSTEMCTL} enable ${SYSTEMD_PATH} || return $?
        fi
    fi
}

####################################################################################

SOFT_NAME=_PACKAGE_NAME_
ROOT_DIR=____ROOT____DIR____
SYSTEM_USER=_SYSTEM_USER_
VAR_PATH=${ROOT_DIR}var/lib/${SYSTEM_USER}

SYSTEMD_SERVICE=martingale.service
SYSTEMD_PATH=${ROOT_DIR}usr/share/${SOFT_NAME}/config/${SYSTEMD_SERVICE}

MARTINGALE_EXEC_FILES="_EXEC_FILES_"
MARTINGALE_CONFIG_FILES="_CONFIG_FILES_"

####################################################################################

if [ -f /usr/share/debconf/confmodule ]
then
    . /usr/share/debconf/confmodule
fi

configure_martingale

if [ -f /usr/share/dbconfig-common/dpkg/postinst.pgsql ]; then
    . /usr/share/dbconfig-common/dpkg/postinst.pgsql
    dbc_pgsql_createdb_encoding="UTF8"
    dbc_generate_include_args="-o template_infile=${ROOT_DIR}usr/share/doc/${SOFT_NAME}/skels/postgresql-config.php"
    dbc_generate_include=template:${ROOT_DIR}etc/${SOFT_NAME}/postgresql-config.php
    dbc_generate_include_owner=${SYSTEM_USER}:${SYSTEM_USER}
    dbc_generate_include_perms=0640
    dbc_go ${SOFT_NAME} "$@"
fi

if [ "$1" = "configure" ]
then
  if [ -n "$2" ]
  then
    if [ -d /run/systemd/system ]
    then
        if ${SYSTEMCTL} is-enabled ${SYSTEMD_SERVICE} 1>/dev/null 2>/dev/null
        then
            ${SYSTEMCTL} daemon-reload
            ${SYSTEMCTL} start ${SYSTEMD_SERVICE} || return $?
        fi
    fi
  else
    if [ -d /run/systemd/system ]
    then
        if ${SYSTEMCTL} is-enabled ${SYSTEMD_SERVICE} 1>/dev/null 2>/dev/null
        then
            ${SYSTEMCTL} daemon-reload
            ${SYSTEMCTL} start ${SYSTEMD_SERVICE} || return $?
        fi
    fi
  fi
fi

if [ "$1" = "install" ]
then
    if [ -d /run/systemd/system ]
    then
        if ${SYSTEMCTL} is-enabled ${SYSTEMD_SERVICE} 1>/dev/null 2>/dev/null
        then
            ${SYSTEMCTL} daemon-reload
            ${SYSTEMCTL} start ${SYSTEMD_SERVICE} || return $?
        fi
    fi
fi

if [ "$1" = "upgrade" ]
then
    if [ -d /run/systemd/system ]
    then
        if ${SYSTEMCTL} is-enabled ${SYSTEMD_SERVICE} 1>/dev/null 2>/dev/null
        then
            ${SYSTEMCTL} daemon-reload
            ${SYSTEMCTL} start ${SYSTEMD_SERVICE} || return $?
        fi
    fi
fi


