#!/bin/bash

RPL=/usr/bin/rpl
CP=/bin/cp
RM=/bin/rm
USERADD=/usr/sbin/useradd
USERDEL=/usr/sbin/userdel
OPENSSL=/usr/bin/openssl
CHOWN=/bin/chown
CHMOD=/bin/chmod
MKDIR=/bin/mkdir
LN=/bin/ln
CAT=/bin/cat
ECHO=/bin/echo
MKTEMP=/bin/mktemp
PWGEN=/usr/bin/pwgen
BASENAME=/usr/bin/basename
UPDATE_RC_D=/usr/sbin/update-rc.d
SYSTEMCTL=/bin/systemctl

SOFT_NAME=_PACKAGE_NAME_
ROOT_DIR=____ROOT____DIR____
SYSTEM_USER=_SYSTEM_USER_
VAR_PATH=${ROOT_DIR}var/lib/${SYSTEM_USER}

SYSTEMD_SERVICE=martingale.service

if [ "$1" = "upgrade" ]
then
  if [ -n "$2" ]
  then
    if [ -d /run/systemd/system ]
    then
        if ${SYSTEMCTL} is-enabled ${SYSTEMD_SERVICE} 1>/dev/null 2>/dev/null
        then
            ${SYSTEMCTL} stop ${SYSTEMD_SERVICE}
        fi
    fi
  fi
fi

if [ "$1" = "install" ]
then
  ${USERADD} -d ${VAR_PATH} -m -s /bin/bash ${SYSTEM_USER}
fi






