#!/bin/bash

RPL=/usr/bin/rpl
CP=/bin/cp
RM=/bin/rm
USERADD=/usr/sbin/useradd
USERDEL=/usr/sbin/userdel
OPENSSL=/usr/bin/openssl
CHOWN=/bin/chown
CHMOD=/bin/chmod
MKDIR=/bin/mkdir
LN=/bin/ln
CAT=/bin/cat
ECHO=/bin/echo
MKTEMP=/bin/mktemp
PWGEN=/usr/bin/pwgen
BASENAME=/usr/bin/basename
UPDATE_RC_D=/usr/sbin/update-rc.d
SYSTEMCTL=/bin/systemctl

SOFT_NAME=_PACKAGE_NAME_
ROOT_DIR=____ROOT____DIR____
SYSTEM_USER=_SYSTEM_USER_
VAR_PATH=${ROOT_DIR}var/lib/${SYSTEM_USER}

SYSTEMD_SERVICE=martingale.service

if [ -f /usr/share/debconf/confmodule ]
then
    . /usr/share/debconf/confmodule
fi

if [ "$1" = "remove" ]
then
    if ${SYSTEMCTL} is-enabled ${SYSTEMD_SERVICE} 1>/dev/null 2>/dev/null
    then
        ${SYSTEMCTL} stop ${SYSTEMD_SERVICE}
        ${SYSTEMCTL} disable ${SYSTEMD_SERVICE}
    fi
    
    if [ -f /usr/share/dbconfig-common/dpkg/prerm.pgsql ]
    then
        . /usr/share/dbconfig-common/dpkg/prerm.pgsql
        dbc_go ${SOFT_NAME} $@
    fi
fi

