#!/bin/bash

REALPATH=/usr/bin/realpath

REL_PATH="usr/sbin/etdtd-daemon"

REAL_PATH=`${REALPATH} "$0"`

ROOT_DIR="${REAL_PATH%${REL_PATH}}"

ACTIVATE_FILE=${ROOT_DIR}usr/lib/ehdtd-daemon/ehdtd-daemon-virtenv/bin/activate

EXEC_PY="ehdtd_daemon"

if [ -f ${ACTIVATE_FILE} ]
then
    source ${ACTIVATE_FILE}
    ${EXEC_PY} $@
    deactivate
fi



