#!/bin/bash

RPL=/usr/bin/rpl
CP=/bin/cp
RM=/bin/rm
USERADD=/usr/sbin/useradd
USERDEL=/usr/sbin/userdel
OPENSSL=/usr/bin/openssl
CHOWN=/bin/chown
CHMOD=/bin/chmod
MKDIR=/bin/mkdir
LN=/bin/ln
CAT=/bin/cat
ECHO=/bin/echo
MKTEMP=/bin/mktemp
PWGEN=/usr/bin/pwgen
UPDATE_RC_D=/usr/sbin/update-rc.d

####################################################################################

SOFT_NAME=ehdtd-daemon
SYSTEM_DIR=/usr/lib/${SOFT_NAME}
ROOT_DIR="/"

####################################################################################

if [ -f /usr/share/dbconfig-common/dpkg/postinst ]
then
    . /usr/share/dbconfig-common/dpkg/postinst
    dbc_generate_include="template:/etc/ehdtd-daemon/ehdtd-daemon.conf"
    dbc_dbuser=ehdtd_daemon
    dbc_dbname=ehdtd_daemon

    dbc_go ehdtd-daemon "$@"
fi

if [ -f /usr/share/dbconfig-common/dpkg/postinst ]; then
    . /usr/share/dbconfig-common/dpkg/postinst
    dbc_createdb_encoding="UTF8"
    dbc_generate_include_args="-o template_infile=${ROOT_DIR}usr/share/${SOFT_NAME}/config-skels/${SOFT_NAME}-config.yaml"
    dbc_generate_include=template:${ROOT_DIR}etc/${SOFT_NAME}/postgresql-config.php
    dbc_generate_include_owner=${SYSTEM_USER}:${SYSTEM_USER}
    dbc_generate_include_perms=0640
    dbc_go ${SOFT_NAME} "$@"
fi
