#!/bin/bash
#
# Install / upgrade database.

set -e

SOFT_NAME=__SOFT_NAME__

action=upgrade

if [ -f /usr/share/debconf/confmodule ]
then
    . /usr/share/debconf/confmodule
fi

if [ -f /usr/share/dbconfig-common/dpkg/config ]; then
	dbc_dbtypes="mysql, pgsql"
	dbc_authmethod_user="password"
	dbc_dbname="${SOFT_NAME}"
	dbc_dbuser="${SOFT_NAME}"
	dbc_ssl="true"

	. /usr/share/dbconfig-common/dpkg/config
	dbc_go ${SOFT_NAME} "$@"
fi

exit 0
