#!/bin/bash

RPL=/usr/bin/rpl
CP=/bin/cp
RM=/bin/rm
USERADD=/usr/sbin/useradd
USERDEL=/usr/sbin/userdel
OPENSSL=/usr/bin/openssl
CHOWN=/bin/chown
CHMOD=/bin/chmod
MKDIR=/bin/mkdir
LN=/bin/ln
CAT=/bin/cat
ECHO=/bin/echo
MKTEMP=/bin/mktemp
PWGEN=/usr/bin/pwgen
UPDATE_RC_D=/usr/sbin/update-rc.d

####################################################################################

SOFT_NAME=__SOFT_NAME__

SYSTEM_DIR=/usr/lib/${SOFT_NAME}

####################################################################################

if [ -f /usr/share/debconf/confmodule ]
then
    . /usr/share/debconf/confmodule
fi

if [ -f /usr/share/dbconfig-common/dpkg/postrm ]; then
    . /usr/share/dbconfig-common/dpkg/postrm
    dbc_go ${SOFT_NAME} "$@"
fi
